/**
 * Data access layer. Combines the local seed stories with real
 * Claude-generated stories from Supabase (written by scripts/fetch-rss.ts +
 * scripts/process-articles.ts) — merged, not replaced, so the curated demo
 * set stays reliable even as the live pipeline's output varies day to day.
 * Everything above this file only ever speaks in the `Story`/`StoryWithPosts`
 * domain types, so this is the only file a data-source change touches.
 */
import type {
  Category,
  Entities,
  Fact,
  Perspective,
  Post,
  Source,
  StandaloneSeedPost,
  StoryWithPosts,
} from "@/types/domain";
import seedStories from "@/lib/data/seed-stories.json";
import seedStandalonePosts from "@/lib/data/seed-standalone-posts.json";
import { createClient } from "@/lib/supabase/server";
import { LOCALE } from "@/lib/locale";

/** The static seed set is English-only demo content — only relevant while
 * running in English mode. In Hebrew mode it would otherwise sit permanently
 * mixed into every listing, search, and category filter alongside real
 * generated Hebrew stories. Gated (not deleted) so switching back to English
 * later restores it automatically. */
const stories = LOCALE === "en" ? (seedStories as unknown as StoryWithPosts[]) : [];
const standalonePosts = LOCALE === "en" ? (seedStandalonePosts as unknown as StandaloneSeedPost[]) : [];

interface GeneratedStoryRow {
  id: string;
  slug: string;
  title: string;
  category: Category;
  summary: string;
  what_happened: string;
  timeline: unknown;
  perspective_a: unknown;
  perspective_b: unknown;
  key_differences_cause: string;
  key_differences_impact: string;
  sources: unknown;
  entities: unknown;
  published_at: string;
  reading_time_minutes: number;
  image_url: string | null;
  archived_at: string | null;
}

interface GeneratedPostRow {
  id: string;
  story_id: string;
  display_name: string;
  perspective: string;
  content: string;
  is_generated: boolean;
  like_count: number;
  reply_count: number;
  created_at: string;
}

/**
 * `generateStaticParams` (build time, no request) and the odd static-render
 * attempt Next makes before bailing to dynamic both surface as a
 * "Dynamic server usage ... cookies" error from the Supabase client — that's
 * Next's own expected signal to re-render this route dynamically, not a
 * real failure, so it's not worth logging as one. Anything else genuinely
 * is a problem and gets logged.
 */
function logStoryFetchError(label: string, err: unknown): void {
  const message = err instanceof Error ? err.message : String(err);
  if (message.includes("Dynamic server usage")) return;
  console.error(`${label}:`, message);
}

function mapPostRow(row: GeneratedPostRow): Post {
  return {
    id: row.id,
    storyId: row.story_id,
    displayName: row.display_name,
    perspective: row.perspective === "B" ? "B" : "A",
    content: row.content,
    isGenerated: row.is_generated,
    likeCount: row.like_count,
    replyCount: row.reply_count,
    createdAt: row.created_at,
  };
}

function mapStoryRow(row: GeneratedStoryRow, postRows: GeneratedPostRow[]): StoryWithPosts {
  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    category: row.category,
    summary: row.summary,
    whatHappened: row.what_happened,
    timeline: row.timeline as Fact[],
    perspectiveA: row.perspective_a as Perspective,
    perspectiveB: row.perspective_b as Perspective,
    keyDifferencesCause: row.key_differences_cause,
    keyDifferencesImpact: row.key_differences_impact,
    sources: row.sources as Source[],
    entities: row.entities as Entities,
    publishedAt: row.published_at,
    readingTimeMinutes: row.reading_time_minutes,
    imageUrl: row.image_url ?? undefined,
    archivedAt: row.archived_at ?? undefined,
    posts: postRows.map(mapPostRow),
  };
}

/** Real stories generated by the pipeline. Never throws — a Supabase hiccup
 * degrades to an empty list (seed stories still show) rather than crashing
 * every page that reads through this repository. */
async function getGeneratedStories(options?: { archivedOnly?: boolean }): Promise<StoryWithPosts[]> {
  try {
    const supabase = await createClient();
    let query = supabase.from("stories").select("*");
    query = options?.archivedOnly
      ? query.not("archived_at", "is", null).order("archived_at", { ascending: false })
      : query.is("archived_at", null).order("published_at", { ascending: false });
    const { data: storyRows, error: storiesError } = await query;

    if (storiesError) {
      logStoryFetchError("Error fetching generated stories", storiesError.message);
      return [];
    }
    if (!storyRows || storyRows.length === 0) return [];

    const storyIds = storyRows.map((row) => row.id);
    const { data: postRows, error: postsError } = await supabase
      .from("posts")
      .select("*")
      .in("story_id", storyIds);

    if (postsError) {
      logStoryFetchError("Error fetching generated posts", postsError.message);
    }

    const postsByStoryId = new Map<string, GeneratedPostRow[]>();
    for (const row of (postRows ?? []) as unknown as GeneratedPostRow[]) {
      const list = postsByStoryId.get(row.story_id) ?? [];
      list.push(row);
      postsByStoryId.set(row.story_id, list);
    }

    return (storyRows as unknown as GeneratedStoryRow[]).map((row) =>
      mapStoryRow(row, postsByStoryId.get(row.id) ?? []),
    );
  } catch (err) {
    logStoryFetchError("Error loading generated stories from Supabase", err);
    return [];
  }
}

export async function getAllStories(): Promise<StoryWithPosts[]> {
  const generated = await getGeneratedStories();
  return [...generated, ...stories];
}

/** Stories removed from the main feed (cap eviction or dedup merge), newest
 * archived first — for the History tab. The static seed set is never
 * archived, so this only ever reflects real generated stories. */
export async function getArchivedStories(): Promise<StoryWithPosts[]> {
  return getGeneratedStories({ archivedOnly: true });
}

/** How long a story keeps showing the "Updated" marker after a reader-trend
 * or new-coverage update — long enough to be seen across a normal browsing
 * session, short enough that the marker doesn't just become permanent
 * background noise. */
const RECENT_UPDATE_WINDOW_HOURS = 48;

/** Maps storyId -> the most recent qualifying update type, for stories
 * updated within the window above. Deliberately excludes "merge" (dedup
 * consolidating a duplicate) — that's bookkeeping, not new context added to
 * the story the way a reader trend or fresh coverage is. */
export async function getRecentStoryUpdateTypes(): Promise<Map<string, "trend" | "coverage">> {
  try {
    const supabase = await createClient();
    const since = new Date(Date.now() - RECENT_UPDATE_WINDOW_HOURS * 60 * 60 * 1000).toISOString();
    const { data, error } = await supabase
      .from("story_updates")
      .select("story_id, update_type, created_at")
      .in("update_type", ["trend", "coverage"])
      .gte("created_at", since)
      .order("created_at", { ascending: false });

    if (error) {
      logStoryFetchError("Error fetching recent story updates", error.message);
      return new Map();
    }

    const map = new Map<string, "trend" | "coverage">();
    for (const row of (data ?? []) as { story_id: string; update_type: "trend" | "coverage" }[]) {
      if (!map.has(row.story_id)) map.set(row.story_id, row.update_type);
    }
    return map;
  } catch (err) {
    logStoryFetchError("Error loading recent story updates from Supabase", err);
    return new Map();
  }
}

export async function getStoryBySlug(
  rawSlug: string,
): Promise<StoryWithPosts | undefined> {
  // The dynamic route's `params.slug` sometimes arrives still
  // percent-encoded (observed to differ between generateMetadata and the
  // page component for the same request, for non-ASCII slugs — a Next.js
  // 16 quirk). decodeURIComponent is a safe no-op on an already-decoded
  // string, so normalizing here covers both cases.
  let slug = rawSlug;
  try {
    slug = decodeURIComponent(rawSlug);
  } catch {
    // Malformed percent-encoding — fall back to the raw value.
  }

  const seedMatch = stories.find((story) => story.slug === slug);
  if (seedMatch) return seedMatch;

  try {
    const supabase = await createClient();
    const { data: storyRow, error: storyError } = await supabase
      .from("stories")
      .select("*")
      .eq("slug", slug)
      .maybeSingle();

    if (storyError || !storyRow) return undefined;

    const { data: postRows, error: postsError } = await supabase
      .from("posts")
      .select("*")
      .eq("story_id", storyRow.id);

    if (postsError) {
      logStoryFetchError("Error fetching posts for generated story", postsError.message);
    }

    return mapStoryRow(
      storyRow as unknown as GeneratedStoryRow,
      (postRows ?? []) as unknown as GeneratedPostRow[],
    );
  } catch (err) {
    logStoryFetchError("Error loading generated story from Supabase", err);
    return undefined;
  }
}

/** Seeded posts with no related story — only shown on the general Posts feed. */
export async function getStandaloneSeedPosts(): Promise<StandaloneSeedPost[]> {
  return standalonePosts;
}

