/**
 * Data access layer. Combines the local seed stories with real
 * Claude-generated stories from Supabase (written by scripts/fetch-rss.ts +
 * scripts/process-articles.ts) — merged, not replaced, so the curated demo
 * set stays reliable even as the live pipeline's output varies day to day.
 * Everything above this file only ever speaks in the `Story`/`StoryWithPosts`
 * domain types, so this is the only file a data-source change touches.
 */
import type {
  Category,
  Entities,
  Fact,
  Perspective,
  Post,
  Source,
  StandaloneSeedPost,
  StoryWithPosts,
} from "@/types/domain";
import seedStories from "@/lib/data/seed-stories.json";
import seedStandalonePosts from "@/lib/data/seed-standalone-posts.json";
import { createClient } from "@/lib/supabase/server";

const stories = seedStories as unknown as StoryWithPosts[];
const standalonePosts = seedStandalonePosts as unknown as StandaloneSeedPost[];

interface GeneratedStoryRow {
  id: string;
  slug: string;
  title: string;
  category: Category;
  summary: string;
  what_happened: string;
  timeline: unknown;
  perspective_a: unknown;
  perspective_b: unknown;
  key_differences_cause: string;
  key_differences_impact: string;
  sources: unknown;
  entities: unknown;
  published_at: string;
  reading_time_minutes: number;
}

interface GeneratedPostRow {
  id: string;
  story_id: string;
  display_name: string;
  perspective: string;
  content: string;
  is_generated: boolean;
  like_count: number;
  reply_count: number;
  created_at: string;
}

/**
 * `generateStaticParams` (build time, no request) and the odd static-render
 * attempt Next makes before bailing to dynamic both surface as a
 * "Dynamic server usage ... cookies" error from the Supabase client — that's
 * Next's own expected signal to re-render this route dynamically, not a
 * real failure, so it's not worth logging as one. Anything else genuinely
 * is a problem and gets logged.
 */
function logStoryFetchError(label: string, err: unknown): void {
  const message = err instanceof Error ? err.message : String(err);
  if (message.includes("Dynamic server usage")) return;
  console.error(`${label}:`, message);
}

function mapPostRow(row: GeneratedPostRow): Post {
  return {
    id: row.id,
    storyId: row.story_id,
    displayName: row.display_name,
    perspective: row.perspective === "B" ? "B" : "A",
    content: row.content,
    isGenerated: row.is_generated,
    likeCount: row.like_count,
    replyCount: row.reply_count,
    createdAt: row.created_at,
  };
}

function mapStoryRow(row: GeneratedStoryRow, postRows: GeneratedPostRow[]): StoryWithPosts {
  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    category: row.category,
    summary: row.summary,
    whatHappened: row.what_happened,
    timeline: row.timeline as Fact[],
    perspectiveA: row.perspective_a as Perspective,
    perspectiveB: row.perspective_b as Perspective,
    keyDifferencesCause: row.key_differences_cause,
    keyDifferencesImpact: row.key_differences_impact,
    sources: row.sources as Source[],
    entities: row.entities as Entities,
    publishedAt: row.published_at,
    readingTimeMinutes: row.reading_time_minutes,
    posts: postRows.map(mapPostRow),
  };
}

/** Real stories generated by the pipeline. Never throws — a Supabase hiccup
 * degrades to an empty list (seed stories still show) rather than crashing
 * every page that reads through this repository. */
async function getGeneratedStories(): Promise<StoryWithPosts[]> {
  try {
    const supabase = await createClient();
    const { data: storyRows, error: storiesError } = await supabase
      .from("stories")
      .select("*")
      .order("published_at", { ascending: false });

    if (storiesError) {
      logStoryFetchError("Error fetching generated stories", storiesError.message);
      return [];
    }
    if (!storyRows || storyRows.length === 0) return [];

    const storyIds = storyRows.map((row) => row.id);
    const { data: postRows, error: postsError } = await supabase
      .from("posts")
      .select("*")
      .in("story_id", storyIds);

    if (postsError) {
      logStoryFetchError("Error fetching generated posts", postsError.message);
    }

    const postsByStoryId = new Map<string, GeneratedPostRow[]>();
    for (const row of (postRows ?? []) as unknown as GeneratedPostRow[]) {
      const list = postsByStoryId.get(row.story_id) ?? [];
      list.push(row);
      postsByStoryId.set(row.story_id, list);
    }

    return (storyRows as unknown as GeneratedStoryRow[]).map((row) =>
      mapStoryRow(row, postsByStoryId.get(row.id) ?? []),
    );
  } catch (err) {
    logStoryFetchError("Error loading generated stories from Supabase", err);
    return [];
  }
}

export async function getAllStories(): Promise<StoryWithPosts[]> {
  const generated = await getGeneratedStories();
  return [...generated, ...stories];
}

export async function getStoryBySlug(
  slug: string,
): Promise<StoryWithPosts | undefined> {
  const seedMatch = stories.find((story) => story.slug === slug);
  if (seedMatch) return seedMatch;

  try {
    const supabase = await createClient();
    const { data: storyRow, error: storyError } = await supabase
      .from("stories")
      .select("*")
      .eq("slug", slug)
      .maybeSingle();

    if (storyError || !storyRow) return undefined;

    const { data: postRows, error: postsError } = await supabase
      .from("posts")
      .select("*")
      .eq("story_id", storyRow.id);

    if (postsError) {
      logStoryFetchError("Error fetching posts for generated story", postsError.message);
    }

    return mapStoryRow(
      storyRow as unknown as GeneratedStoryRow,
      (postRows ?? []) as unknown as GeneratedPostRow[],
    );
  } catch (err) {
    logStoryFetchError("Error loading generated story from Supabase", err);
    return undefined;
  }
}

/** Seeded posts with no related story — only shown on the general Posts feed. */
export async function getStandaloneSeedPosts(): Promise<StandaloneSeedPost[]> {
  return standalonePosts;
}

/**
 * Seed-only slugs, for `generateStaticParams` — that hook runs at build
 * time with no HTTP request in scope, so it can't use the cookies-based
 * Supabase client that `getAllStories()` now needs for generated stories.
 * The app renders every story page dynamically anyway (per-request, since
 * the root layout checks auth), so this only pre-renders the stable seed
 * set; generated-story slugs still render fine on demand at request time.
 */
export function getSeedStorySlugs(): string[] {
  return stories.map((story) => story.slug);
}
